name: GSI - Erfan

on: [push]

env:
  ROM: Flyme
  GENERIC_TYPE: 0
  ROM_GENERIC: AncientOS
  ROM_LINK: https://download.meizu.com/Firmware/Flyme/16xs/8.20.8.4/cn_daily/20200804003619/e02f211f/update.zip
  DLAONLYSF: https://sourceforge.net/projects/yumi-project/gsi/Flyme/meizu16Xs/20200804/Flyme-Aonly-10-20200804-ErfanGSI-YuMiGSI.zip/download
  DLABSF: https://sourceforge.net/projects/yumi-project/gsi/Flyme/meizu16Xs/20200804/Flyme-AB-10-20200804-ErfanGSI-YuMiGSI.zip/download
  SFDIRA: cd /home/pfs/project/yumi-project/gsi/Flyme/meizu16Xs/20200804
  SFDIRAB: cd /home/pfs/project/yumi-project/gsi/Flyme/meizu16Xs/20200804
  MIR: gof
  TZ: America/Sao_Paulo
  READ: Use <b>Disable HW Overlays ZIP</b> to avoid UI issues or related.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x $ROM/initial.sh
              . $ROM/initial.sh
       
       - name: Clone ErfanGSI Source Code
         run: git clone https://github.com/yukosky/ErfanGSIs -b runner
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.TOKEN }}
              
         run: |
               chmod +x $ROM/build.sh
               . $ROM/build.sh
               
       - name: Copy and rename A-Only build info
         run: cp ErfanGSIs/output/*Aonly*.txt Aonly.txt

       - name: Upload to SF
         run: |
              cd ErfanGSIs/output
              expect -c "
              spawn sftp pything@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA\r\"
              set timeout -1
              send \"put *Aonly*.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp pything@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"sftp> \"
              send \"$SFDIRAB\r\"
              set timeout -1
              send \"put *AB*.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"

       - name: Send build info to Telegram
         env:
              CHAT_ID: ${{ secrets.CHAT_ID }}
              TOKEN: ${{ secrets.TOKEN }}
              API_ID: ${{ secrets.API_ID }}
              API_HASH: ${{ secrets.API_HASH }}

         run: |
              chmod +x upload.sh
              ./upload.sh
